package de.bund.digitalservice.ris.norms.application.service

import de.bund.digitalservice.ris.norms.application.port.input.EditNormFrameUseCase
import de.bund.digitalservice.ris.norms.application.port.output.EditNormOutputPort
import de.bund.digitalservice.ris.norms.domain.entity.Norm
import org.springframework.stereotype.Service
import reactor.core.publisher.Mono
import java.util.UUID

@Service
class EditNormFrameService(private val editNormOutputPort: EditNormOutputPort) :
    EditNormFrameUseCase {

    override fun editNormFrame(command: EditNormFrameUseCase.Command): Mono<Boolean> {
        val norm = getUpdatedNorm(command.guid, command.properties)
        val editNormCommand = EditNormOutputPort.Command(norm)
        return editNormOutputPort.editNorm(editNormCommand)
    }
}

private fun getUpdatedNorm(guid: UUID, properties: EditNormFrameUseCase.NormFrameProperties) = Norm(
    guid = guid,
    articles = listOf(),
    metadataSections = properties.metadataSections,
    officialLongTitle = properties.officialLongTitle,
    risAbbreviation = properties.risAbbreviation,
    documentNumber = properties.documentNumber,
    documentCategory = properties.documentCategory,
    documentTypeName = properties.documentTypeName,
    documentNormCategory = properties.documentNormCategory,
    documentTemplateName = properties.documentTemplateName,
    providerEntity = properties.providerEntity,
    providerDecidingBody = properties.providerDecidingBody,
    providerIsResolutionMajority = properties.providerIsResolutionMajority,
    officialShortTitle = properties.officialShortTitle,
    officialAbbreviation = properties.officialAbbreviation,
    entryIntoForceDate = properties.entryIntoForceDate,
    entryIntoForceDateState = properties.entryIntoForceDateState,
    principleEntryIntoForceDate = properties.principleEntryIntoForceDate,
    principleEntryIntoForceDateState = properties.principleEntryIntoForceDateState,
    divergentEntryIntoForceDate = properties.divergentEntryIntoForceDate,
    divergentEntryIntoForceDateState = properties.divergentEntryIntoForceDateState,
    entryIntoForceNormCategory = properties.entryIntoForceNormCategory,
    expirationDate = properties.expirationDate,
    expirationDateState = properties.expirationDateState,
    isExpirationDateTemp = properties.isExpirationDateTemp,
    principleExpirationDate = properties.principleExpirationDate,
    principleExpirationDateState = properties.principleExpirationDateState,
    divergentExpirationDate = properties.divergentExpirationDate,
    divergentExpirationDateState = properties.divergentExpirationDateState,
    expirationNormCategory = properties.expirationNormCategory,
    announcementDate = properties.announcementDate,
    publicationDate = properties.publicationDate,
    printAnnouncementGazette = properties.printAnnouncementGazette,
    printAnnouncementYear = properties.printAnnouncementYear,
    printAnnouncementNumber = properties.printAnnouncementNumber,
    printAnnouncementPage = properties.printAnnouncementPage,
    printAnnouncementInfo = properties.printAnnouncementInfo,
    printAnnouncementExplanations = properties.printAnnouncementExplanations,
    digitalAnnouncementMedium = properties.digitalAnnouncementMedium,
    digitalAnnouncementDate = properties.digitalAnnouncementDate,
    digitalAnnouncementEdition = properties.digitalAnnouncementEdition,
    digitalAnnouncementYear = properties.digitalAnnouncementYear,
    digitalAnnouncementPage = properties.digitalAnnouncementPage,
    digitalAnnouncementArea = properties.digitalAnnouncementArea,
    digitalAnnouncementAreaNumber = properties.digitalAnnouncementAreaNumber,
    digitalAnnouncementInfo = properties.digitalAnnouncementInfo,
    digitalAnnouncementExplanations = properties.digitalAnnouncementExplanations,
    euAnnouncementGazette = properties.euAnnouncementGazette,
    euAnnouncementYear = properties.euAnnouncementYear,
    euAnnouncementSeries = properties.euAnnouncementSeries,
    euAnnouncementNumber = properties.euAnnouncementNumber,
    euAnnouncementPage = properties.euAnnouncementPage,
    euAnnouncementInfo = properties.euAnnouncementInfo,
    euAnnouncementExplanations = properties.euAnnouncementExplanations,
    otherOfficialAnnouncement = properties.otherOfficialAnnouncement,
    completeCitation = properties.completeCitation,
    statusNote = properties.statusNote,
    statusDescription = properties.statusDescription,
    statusDate = properties.statusDate,
    statusReference = properties.statusReference,
    repealNote = properties.repealNote,
    repealArticle = properties.repealArticle,
    repealDate = properties.repealDate,
    repealReferences = properties.repealReferences,
    reissueNote = properties.reissueNote,
    reissueArticle = properties.reissueArticle,
    reissueDate = properties.reissueDate,
    reissueReference = properties.reissueReference,
    otherStatusNote = properties.otherStatusNote,
    documentStatusWorkNote = properties.documentStatusWorkNote,
    documentStatusDescription = properties.documentStatusDescription,
    documentStatusDate = properties.documentStatusDate,
    documentStatusReference = properties.documentStatusReference,
    documentStatusEntryIntoForceDate = properties.documentStatusEntryIntoForceDate,
    documentStatusProof = properties.documentStatusProof,
    documentTextProof = properties.documentTextProof,
    otherDocumentNote = properties.otherDocumentNote,
    applicationScopeArea = properties.applicationScopeArea,
    applicationScopeStartDate = properties.applicationScopeStartDate,
    applicationScopeEndDate = properties.applicationScopeEndDate,
    categorizedReference = properties.categorizedReference,
    otherFootnote = properties.otherFootnote,
    footnoteChange = properties.footnoteChange,
    footnoteComment = properties.footnoteComment,
    footnoteDecision = properties.footnoteDecision,
    footnoteStateLaw = properties.footnoteStateLaw,
    footnoteEuLaw = properties.footnoteEuLaw,
    digitalEvidenceLink = properties.digitalEvidenceLink,
    digitalEvidenceRelatedData = properties.digitalEvidenceRelatedData,
    digitalEvidenceExternalDataNote = properties.digitalEvidenceExternalDataNote,
    digitalEvidenceAppendix = properties.digitalEvidenceAppendix,
    celexNumber = properties.celexNumber,
    text = properties.text,
)
