package de.bund.digitalservice.ris.caselaw.domain;

public enum ProceedingType {
  VERFASSUNGSBESCHWERDE,
  ORGANSTREITVERFAHREN,
  KONKRETE_NORMENKONTROLLE,
  ABSTRAKTE_NORMENKONTROLLE,
  BUND_LAENDER_STREITIGKEIT,
  WAHLPRUEFUNGSVERFAHREN,
  EINSTWEILIGER_RECHTSSCHUTZ,
  SONSTIGE_VERFAHREN
}
