version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/Berlin"
    cooldown:
      default-days: 3
    groups:
      all-frontend-non-major-dependencies:
        update-types:
          - minor
          - patch
      tiptap:
        patterns:
          - "@tiptap/*"
    ignore:
      # later versions have a bug that reports false positives
      - dependency-name: "eslint-plugin-testing-library"
        versions: [ ">7.6.3" ]
      # we won't fix new eslint rule violations for deprecated e2e tests
      - dependency-name: "eslint-plugin-playwright"
        versions: [ ">=2.9.0" ]
      - dependency-name: "eslint"
        versions: [ ">=10.0.0" ]
      - dependency-name: "@eslint/js"
        versions: [ ">=10.0.0" ]
      - dependency-name: "vite"
        versions: [ ">=8.0.0" ]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/Berlin"
    cooldown:
      default-days: 3
    ignore:
      - dependency-name: "postgres"
        update-types:
          - version-update:semver-major

  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/Berlin"
    cooldown:
      default-days: 3
    groups:
      all-backend-non-major-dependencies:
        update-types:
          - minor
          - patch
        exclude-patterns:
          - de.bund.digitalservice:*

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/Berlin"
    cooldown:
      default-days: 3
