FROM node:22.21.0 AS builder
WORKDIR /usr/src/app
COPY . .
RUN npm install && npx vite build

FROM cgr.dev/chainguard/nginx@sha256:e6ea656575990c50beb48673cacfc2e761d000588d0b2742b744a2e15f851205
EXPOSE 8081
COPY --from=builder /usr/src/app/dist /var/lib/nginx/html
COPY nginx.conf /etc/nginx/conf.d/ris.conf
