FROM node:22.15.0 AS builder
WORKDIR /usr/src/app
COPY . .
RUN npm install && npx vite build

FROM cgr.dev/chainguard/nginx@sha256:659d9088eaa57ae5428ad4b0dff69af6e445e6dcc2aaaff66a34d71d2401aad7
EXPOSE 8081
COPY --from=builder /usr/src/app/dist /var/lib/nginx/html
COPY nginx.conf /etc/nginx/conf.d/ris.conf
