FROM gradle:9.2-jdk21 AS backend-builder
WORKDIR /app
COPY . /app
RUN --mount=type=secret,id=GH_PACKAGES_REPOSITORY_USER \
    --mount=type=secret,id=GH_PACKAGES_REPOSITORY_TOKEN \
    if [ -f /run/secrets/GH_PACKAGES_REPOSITORY_USER ]; then \
        export GH_PACKAGES_REPOSITORY_USER=$(cat /run/secrets/GH_PACKAGES_REPOSITORY_USER); \
    fi; \
    if [ -f /run/secrets/GH_PACKAGES_REPOSITORY_TOKEN ]; then \
        export GH_PACKAGES_REPOSITORY_TOKEN=$(cat /run/secrets/GH_PACKAGES_REPOSITORY_TOKEN); \
    fi; \
    ./gradlew build -x integrationTest -x test -x spotlessCheck


FROM cgr.dev/chainguard/jre@sha256:819fcd1cf873caf423ea6b4c7b66c82ac8c6506f7a1229c3d8ad7564bab4af54
COPY --from=backend-builder /app/build/libs/ris-backend-service-*.jar /app/app.jar
ENV spring.cloud.bootstrap.enabled=true
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
