<script lang="ts" setup>
import Button from "primevue/button"
import { computed, ref, watch } from "vue"
import { useRouter } from "vue-router"
import LoadingSpinner from "@/components/LoadingSpinner.vue"
import { useScroll } from "@/composables/useScroll"
import { longTextLabels, shortTextLabels } from "@/domain/decision"
import borderNumberService from "@/services/borderNumberService"
import IconCheck from "~icons/ic/baseline-check"
import IconErrorOutline from "~icons/ic/baseline-error-outline"

const emits = defineEmits<{
  borderNumbersRecalculated: []
  borderNumberValidationUpdated: [areBorderNumbersAndLinksValid: boolean]
}>()

const borderNumberValidationResult = ref(
  borderNumberService.validateBorderNumbers(),
)
const borderNumberLinkValidationResult = ref(
  borderNumberService.validateBorderNumberLinks(),
)
const areBorderNumbersAndLinksValid = computed<boolean>(
  () =>
    borderNumberValidationResult.value.isValid &&
    borderNumberLinkValidationResult.value.isValid,
)
watch(areBorderNumbersAndLinksValid, (isValid) =>
  emits("borderNumberValidationUpdated", isValid),
)

// We want to display the action with a fake delay (recalculation only takes a couple of ms)
const showRecalculatingBorderNumbersFakeDelay = ref(false)

async function recalculateBorderNumbers() {
  showRecalculatingBorderNumbersFakeDelay.value = true
  borderNumberService.makeBorderNumbersSequential()

  borderNumberValidationResult.value =
    borderNumberService.validateBorderNumbers()
  borderNumberLinkValidationResult.value =
    borderNumberService.validateBorderNumberLinks()

  setTimeout(
    () => (showRecalculatingBorderNumbersFakeDelay.value = false),
    3_000,
  )
  // Preview is generated by the backend, so the updated border numbers need to be saved first.
  emits("borderNumbersRecalculated")
}

const router = useRouter()
const { scrollIntoViewportById } = useScroll()
async function scrollToCategory(key: string) {
  await router.push({ name: "caselaw-documentUnit-documentNumber-categories" })
  await scrollIntoViewportById(key)
}
</script>
<template>
  <div aria-label="Randnummernprüfung" class="flex flex-col">
    <h2 class="ris-label1-bold mb-16">Randnummernprüfung</h2>

    <div v-if="!areBorderNumbersAndLinksValid">
      <div class="flex flex-row gap-8">
        <IconErrorOutline class="text-red-800" />

        <div class="ris-body1-regular flex flex-col gap-24">
          <div
            v-if="
              !borderNumberValidationResult.isValid &&
              !borderNumberValidationResult.hasError
            "
          >
            Die Reihenfolge der Randnummern ist nicht korrekt.
            <dl class="my-16">
              <div class="grid grid-cols-2 gap-24 px-0">
                <dt class="ris-label2-bold self-center">Rubrik</dt>
                <dd class="ris-body2-regular">
                  <Button
                    class="h-auto border-none p-0!"
                    text
                    variant="link"
                    @click="
                      scrollToCategory(
                        borderNumberValidationResult.invalidCategory,
                      )
                    "
                    >{{
                      longTextLabels[
                        borderNumberValidationResult.invalidCategory
                      ]
                    }}</Button
                  >
                </dd>
              </div>
              <div class="grid grid-cols-2 gap-24 px-0">
                <dt class="ris-label2-bold self-center">
                  Erwartete Randnummer
                </dt>
                <dd class="ris-body2-regular">
                  {{ borderNumberValidationResult.expectedBorderNumber }}
                </dd>
              </div>
              <div class="grid grid-cols-2 gap-24 px-0">
                <dt class="ris-label2-bold self-center">
                  Tatsächliche Randnummer
                </dt>
                <dd class="ris-body2-regular">
                  {{ borderNumberValidationResult.firstInvalidBorderNumber }}
                </dd>
              </div>
            </dl>
          </div>
          <div v-if="!borderNumberLinkValidationResult.isValid">
            Es gibt ungültige Randnummern-Verweise in folgenden Rubriken:
            <ul class="list-disc">
              <li
                v-for="key in borderNumberLinkValidationResult.invalidCategories"
                :key="key"
              >
                <Button
                  class="h-auto border-none p-0!"
                  text
                  variant="link"
                  @click="scrollToCategory(key)"
                >
                  {{
                    shortTextLabels[key as keyof typeof shortTextLabels] ??
                    longTextLabels[key as keyof typeof longTextLabels]
                  }}</Button
                >
              </li>
            </ul>
          </div>
          <div v-if="borderNumberValidationResult.hasError">
            Bei der Randnummernprüfung ist ein Fehler aufgetreten. Bitte prüfen
            Sie die Randnummern manuell und informieren Sie den Support.
          </div>
        </div>
      </div>
      <Button
        v-if="
          !borderNumberValidationResult.isValid &&
          !borderNumberValidationResult.hasError &&
          !showRecalculatingBorderNumbersFakeDelay
        "
        aria-label="Randnummern neu berechnen"
        button-type="tertiary"
        class="mt-8 w-fit"
        label="Randnummern neu berechnen"
        size="small"
        @click="recalculateBorderNumbers"
      />
    </div>
    <div
      v-else-if="!showRecalculatingBorderNumbersFakeDelay"
      class="flex flex-row gap-8"
    >
      <IconCheck class="text-green-700" />
      <p>Die Reihenfolge der Randnummern ist korrekt.</p>
    </div>
    <div
      v-if="showRecalculatingBorderNumbersFakeDelay"
      class="flex flex-row gap-8"
    >
      <LoadingSpinner size="small" />
      <p>Die Randnummern werden neu berechnet</p>
    </div>
  </div>
</template>
