<script lang="ts" setup>
import { storeToRefs } from "pinia"
import { computed, Ref, ref } from "vue"
import CodeSnippet from "@/components/CodeSnippet.vue"
import ExpandableContent from "@/components/ExpandableContent.vue"
import HandoverDuplicateCheckView from "@/components/HandoverDuplicateCheckView.vue"
import BorderNumberCheck from "@/components/publication/BorderNumberCheck.vue"
import DecisionPlausibilityCheck from "@/components/publication/DecisionPlausibilityCheck.vue"
import PublicationActions from "@/components/publication/PublicationActions.vue"
import HandoverTextCheckView from "@/components/text-check/HandoverTextCheckView.vue"
import TitleElement from "@/components/TitleElement.vue"
import { useFeatureToggle } from "@/composables/useFeatureToggle"
import { Decision } from "@/domain/decision"
import { DuplicateRelationStatus } from "@/domain/managementData"
import { useDocumentUnitStore } from "@/stores/documentUnitStore"

const isPortalPublicationEnabled = useFeatureToggle("neuris.portal-publication")
const textCheckAllToggle = useFeatureToggle("neuris.text-check-publication")

const store = useDocumentUnitStore()
const { documentUnit: decision } = storeToRefs(store) as {
  documentUnit: Ref<Decision | undefined>
}

const areBorderNumbersAndLinksValid = ref<boolean>(false)

async function onBorderNumbersRecalculated() {
  // Preview is generated by the backend, so the updated border numbers need to be saved first.
  await store.updateDocumentUnit()
  // await fetchPreview()
}

const isPlausibilityCheckValid = ref(false)
const isPublishable = computed(
  () => isPlausibilityCheckValid.value && isPortalPublicationEnabled.value,
)

const pendingDuplicates = ref(
  decision.value!.managementData?.duplicateRelations?.filter(
    (relation) => relation.status === DuplicateRelationStatus.PENDING,
  ) ?? [],
)
</script>

<template>
  <div class="w-full flex-1 grow p-24">
    <div class="flex w-full flex-col gap-24 bg-white p-24">
      <TitleElement>Veröffentlichen</TitleElement>
      <DecisionPlausibilityCheck
        @update-plausibility-check="
          (isValid) => (isPlausibilityCheckValid = isValid)
        "
      />
      <BorderNumberCheck
        @border-number-validation-updated="
          (isValid) => (areBorderNumbersAndLinksValid = isValid)
        "
        @border-numbers-recalculated="onBorderNumbersRecalculated"
      />
      <HandoverDuplicateCheckView :pending-duplicates="pendingDuplicates" />
      <HandoverTextCheckView
        v-if="textCheckAllToggle"
        :document-id="decision!.uuid"
        :document-number="decision!.documentNumber"
      />
      <div class="border-b-1 border-b-gray-400"></div>
      <ExpandableContent
        v-if="isPlausibilityCheckValid"
        as-column
        class="border-b-1 border-gray-400 pb-24"
        header="XML Vorschau"
        header-class="ris-body1-bold"
        :is-expanded="false"
        title="XML Vorschau"
      >
        <CodeSnippet title="" :xml="'<?xml>' + '\nNoch nicht implementiert'" />
      </ExpandableContent>
      <PublicationActions :is-publishable="isPublishable" />
    </div>
  </div>
</template>
