<script lang="ts" setup>
import { storeToRefs } from "pinia"
import Message from "primevue/message"
import { computed, onBeforeMount, Ref, ref } from "vue"
import CodeSnippet from "@/components/CodeSnippet.vue"
import ExpandableContent from "@/components/ExpandableContent.vue"
import HandoverDuplicateCheckView from "@/components/HandoverDuplicateCheckView.vue"
import { LdmlPreview } from "@/components/input/types"
import BorderNumberCheck from "@/components/publication/BorderNumberCheck.vue"
import DecisionPlausibilityCheck from "@/components/publication/DecisionPlausibilityCheck.vue"
import PublicationActions from "@/components/publication/PublicationActions.vue"
import HandoverTextCheckView from "@/components/text-check/HandoverTextCheckView.vue"
import TitleElement from "@/components/TitleElement.vue"
import { useFeatureToggle } from "@/composables/useFeatureToggle"
import { Decision } from "@/domain/decision"
import { Kind } from "@/domain/documentationUnitKind"
import { DuplicateRelationStatus } from "@/domain/managementData"
import publishDocumentationUnitService from "@/services/publishDocumentationUnitService"
import { useDocumentUnitStore } from "@/stores/documentUnitStore"

const hasPlausibilityCheckPassed = ref(false)
const textCheckAllToggle = useFeatureToggle("neuris.text-check-publication")

const store = useDocumentUnitStore()
const { documentUnit: decision } = storeToRefs(store) as {
  documentUnit: Ref<Decision | undefined>
}

const areBorderNumbersAndLinksValid = ref<boolean>(false)
async function onBorderNumbersRecalculated() {
  // Preview is generated by the backend, so the updated border numbers need to be saved first.
  await store.updateDocumentUnit()
  await fetchPreview()
}

const publicationWarnings = computed(() => {
  const warnings: string[] = []
  if (pendingDuplicates.value?.length)
    warnings.push("Es besteht Dublettenverdacht.")
  if (!areBorderNumbersAndLinksValid.value)
    warnings.push("Die Randnummern sind nicht korrekt.")
  return warnings
})

const isPublishable = computed(
  () => hasPlausibilityCheckPassed.value && !!preview.value?.success,
)
const preview = ref<LdmlPreview>()
const previewError = ref()
const fetchPreview = async () => {
  if (!hasPlausibilityCheckPassed.value) return

  const previewResponse = await publishDocumentationUnitService.getPreview(
    decision.value!.uuid,
  )
  if (previewResponse.error) {
    previewError.value = previewResponse.error
  } else if (previewResponse.data?.ldml) {
    preview.value = previewResponse.data
  }
}

const pendingDuplicates = ref(
  decision.value!.managementData?.duplicateRelations?.filter(
    (relation) => relation.status === DuplicateRelationStatus.PENDING,
  ) ?? [],
)

onBeforeMount(async () => {
  // Save doc unit in case there are any unsaved local changes before fetching ldml preview
  await store.updateDocumentUnit()
  await fetchPreview()
})
</script>

<template>
  <div class="flex w-full flex-1 grow flex-col gap-32 p-24">
    <div class="flex w-full flex-col gap-24 bg-white p-24">
      <TitleElement>Prüfen</TitleElement>
      <DecisionPlausibilityCheck
        @plausibility-check-updated="
          (hasPassed) => (hasPlausibilityCheckPassed = hasPassed)
        "
      />
      <BorderNumberCheck
        @border-number-check-updated="
          (isValid) => (areBorderNumbersAndLinksValid = isValid)
        "
        @border-numbers-recalculated="onBorderNumbersRecalculated"
      />
      <HandoverDuplicateCheckView :pending-duplicates="pendingDuplicates" />
      <HandoverTextCheckView
        v-if="textCheckAllToggle"
        :document-id="decision!.uuid"
        :document-number="decision!.documentNumber"
        :kind="Kind.DECISION"
      />
      <div
        v-if="hasPlausibilityCheckPassed && preview?.success && !!preview.ldml"
        class="border-b-1 border-b-gray-400"
      ></div>
      <ExpandableContent
        v-if="hasPlausibilityCheckPassed && preview?.success && !!preview.ldml"
        as-column
        class="border-b-1 border-gray-400 pb-24"
        :data-set="preview"
        header="LDML Vorschau"
        header-class="ris-body1-bold"
        :is-expanded="false"
        title="LDML Vorschau"
      >
        <CodeSnippet title="" :xml="preview.ldml" />
      </ExpandableContent>
      <Message
        v-if="hasPlausibilityCheckPassed && previewError"
        aria-label="Fehler beim Laden der LDML-Vorschau"
        severity="error"
      >
        <p class="ris-body1-bold">{{ previewError.title }}</p>
        <p>{{ previewError.description }}</p>
      </Message>
    </div>
    <div class="flex w-full flex-col gap-24 bg-white p-24">
      <TitleElement>Veröffentlichen und Zurückziehen</TitleElement>
      <PublicationActions
        :is-publishable="isPublishable"
        :publication-warnings="publicationWarnings"
      />
    </div>
  </div>
</template>
