package de.bund.digitalservice.ris.norms.domain.value

enum class MetadataSectionName {
    NORM,
    SUBJECT_AREA,
    LEAD,
    PARTICIPATION,
    CITATION_DATE,
    AGE_INDICATION,
    OFFICIAL_REFERENCE,
    PRINT_ANNOUNCEMENT,
    DIGITAL_ANNOUNCEMENT,
    EU_ANNOUNCEMENT,
    OTHER_OFFICIAL_ANNOUNCEMENT,
    NORM_PROVIDER,
    DOCUMENT_TYPE,
    DIVERGENT_ENTRY_INTO_FORCE,
    DIVERGENT_ENTRY_INTO_FORCE_DEFINED,
    DIVERGENT_ENTRY_INTO_FORCE_UNDEFINED,
    DIVERGENT_EXPIRATION,
    DIVERGENT_EXPIRATION_DEFINED,
    DIVERGENT_EXPIRATION_UNDEFINED,
}
