export type DocumentationUnitSearchParameter =
  | "documentNumber"
  | "fileNumber"
  | "publicationStatus"
  | "publicationDate"
  | "scheduledOnly"
  | "courtType"
  | "courtLocation"
  | "decisionDate"
  | "decisionDateEnd"
  | "withError"
  | "myDocOfficeOnly"
  | "withDuplicateWarning"
  | "kind"
  | "resolutionDate"
  | "resolutionDateEnd"
  | "isResolved"
