DROP TABLE IF EXISTS
  norms CASCADE;

DROP TABLE IF EXISTS
  articles CASCADE;

DROP TABLE IF EXISTS
  paragraphs CASCADE;

DROP TABLE IF EXISTS
  conclusions CASCADE;

DROP TABLE IF EXISTS
  document_section CASCADE;

DROP TABLE IF EXISTS
  files CASCADE;

DROP TABLE IF EXISTS
  formulas CASCADE;

DROP TABLE IF EXISTS
  metadata_sections CASCADE;

DROP TABLE IF EXISTS
  metadata CASCADE;

DROP TABLE IF EXISTS
  recitals CASCADE;
