openapi: 3.0.0
info:
  version: 0.0.1
  title: NeuRIS Normen Service API
  description: Interface for the normen service of the legal information system
  license:
    name: MIT
    url: https://mit-license.org

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/VICTORDELCAMPO_1/neu-ris_normen_service_api_new/0.0.1
  - url: https://ris.prod.ds4g.net/api/norms
    description: Public production server
  - url: http://localhost:3000
    description: Local development server

paths:
  /norms:
    get:
      summary: Get a list of all available norms
      operationId: getAllNorms
      responses:
        "200":
          description: Successful response with list of allnorms
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Norm"

        "400":
          description: ""

    post:
      summary: Create new norm
      operationId: createNorm
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NormWithoutGuid"
      responses:
        "201":
          description: Norm got successfully created
          headers:
            Location:
              description: URI reference for the new norm
              schema:
                type: string
        "400":
          description: Invalid norm

  /norms/{guid}:
    get:
      summary: Obtain a single norm by its Guid
      operationId: getNormByGuid
      parameters:
        - name: guid
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/Guid"
      responses:
        "200":
          description: Norm was found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Norm"
        "404":
          description: No norm found for this Guid

    patch:
      summary: Edit the frame data of a norm
      operationId: editNormFrame
      parameters:
        - name: guid
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/Guid"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - longTitle
              properties:
                longTitle:
                  type: string
      responses:
        "204":
          description: Norm was updated

        "400":
          description: ""

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    Guid:
      description: The globally unique identifier of the norm (format in UUID)
      type: string
      format: uuid

    ParagraphWithoutGuid:
      type: object
      required:
        - marker
        - text
      properties:
        marker:
          type: string
        text:
          type: string
      example:
        marker: "(1)"
        text: "Dieses Gesetz regelt Mindestziele und deren Sicherstellung bei der Beschaffung bestimmter Straßenfahrzeuge und Dienstleistungen, für die diese Straßenfahrzeuge eingesetzt werden, durch öffentliche Auftraggeber und Sektorenauftraggeber."

    ArticleWithoutGuid:
      type: object
      required:
        - marker
        - paragraphs
      properties:
        marker:
          type: string
        title:
          type: string
        paragraphs:
          type: array
          items:
            $ref: "#/components/schemas/ParagraphWithoutGuid"
      example:
        marker: "§ 1"
        title: "Allgemeiner Anwendungsbereich"
        paragraphs:
          - marker: "(1)"
            text: "Dieses Gesetz regelt Mindestziele und deren Sicherstellung bei der Beschaffung bestimmter Straßenfahrzeuge und Dienstleistungen, für die diese Straßenfahrzeuge eingesetzt werden, durch öffentliche Auftraggeber und Sektorenauftraggeber."

    NormWithoutGuid:
      type: object
      required:
        - longTitle
        - articles
      properties:
        longTitle:
          type: string
        articles:
          type: array
          items:
            $ref: "#/components/schemas/ArticleWithoutGuid"
      example:
        longTitle: "Gesetz über die Beschaffung sauberer Straßenfahrzeuge"
        articles:
          - marker: "§ 1"
            title: "Allgemeiner Anwendungsbereich"
            paragraphs:
              - marker: "(1)"
                text: "Dieses Gesetz regelt Mindestziele und deren Sicherstellung bei der Beschaffung bestimmter Straßenfahrzeuge und Dienstleistungen, für die diese Straßenfahrzeuge eingesetzt werden, durch öffentliche Auftraggeber und Sektorenauftraggeber."

    Paragraph:
      allOf:
        - $ref: "#/components/schemas/ParagraphWithoutGuid"
        - type: object
          required:
            - guid
          properties:
            guid:
              $ref: "#/components/schemas/Guid"
          example:
            guid: "eb6f27c7-79ef-4b25-8aef-b8726f6ed26f"
            marker: "(1)"
            text: "Dieses Gesetz regelt Mindestziele und deren Sicherstellung bei der Beschaffung bestimmter Straßenfahrzeuge und Dienstleistungen, für die diese Straßenfahrzeuge eingesetzt werden, durch öffentliche Auftraggeber und Sektorenauftraggeber."

    Article:
      type: object
      required:
        - guid
        - marker
        - paragraphs
      properties:
        guid:
          $ref: "#/components/schemas/Guid"
        title:
          type: string
        marker:
          type: string
        paragraphs:
          type: array
          items:
            $ref: "#/components/schemas/Paragraph"
      example:
        guid: "07eb4f72-79cb-4070-93b5-62bfb44d3753"
        marker: "§ 1"
        title: "Allgemeiner Anwendungsbereich"
        paragraphs:
          - guid: "eb6f27c7-79ef-4b25-8aef-b8726f6ed26f"
            marker: "(1)"
            text: "Dieses Gesetz regelt Mindestziele und deren Sicherstellung bei der Beschaffung bestimmter Straßenfahrzeuge und Dienstleistungen, für die diese Straßenfahrzeuge eingesetzt werden, durch öffentliche Auftraggeber und Sektorenauftraggeber."

    Norm:
      type: object
      required:
        - guid
        - longTitle
        - articles
      properties:
        guid:
          $ref: "#/components/schemas/Guid"
        longTitle:
          type: string
        articles:
          type: array
          items:
            $ref: "#/components/schemas/Article"
      example:
        guid: "86ee3aa7-b8ec-4f32-a6c7-2c7e13fc7919"
        longTitle: "Gesetz über die Beschaffung sauberer Straßenfahrzeuge"
        articles:
          - guid: "07eb4f72-79cb-4070-93b5-62bfb44d3753"
            marker: "§ 1"
            title: "Allgemeiner Anwendungsbereich"
            paragraphs:
              - guid: "eb6f27c7-79ef-4b25-8aef-b8726f6ed26f"
                marker: "(1)"
                text: "Dieses Gesetz regelt Mindestziele und deren Sicherstellung bei der Beschaffung bestimmter Straßenfahrzeuge und Dienstleistungen, für die diese Straßenfahrzeuge eingesetzt werden, durch öffentliche Auftraggeber und Sektorenauftraggeber."

security:
  - BasicAuth: []
