/* eslint-disable no-irregular-whitespace */
export const noteContent = `Der III. Zivilsenat des Bundesgerichtshofs hat im schriftlichen Verfahren nach § 128 Abs. 2 ZPO, in dem Schriftsätze bis zum 7. Januar 2022 eingereicht werden konnten, durch den Vorsitzenden Richter Dr. Herrmann, den Richter Dr. Remmert, die Richterinnen Dr. Arend und Dr. Böttcher sowie den Richter Dr. Kessen

für Recht erkannt:

Auf die Revision des Klägers wird das Urteil des Oberlandesgerichts Nürnberg - 3. Zivilsenat und Kartellsenat - vom 29. Dezember 2020 teilweise aufgehoben und wie folgt neu gefasst:

Auf die Berufung des Klägers wird das Urteil des Landgerichts Nürnberg-Fürth - 11. Zivilkammer - vom 20. Mai 2020 unter Zurückweisung der weitergehenden Berufung teilweise abgeändert und insgesamt wie folgt neu gefasst:

Die Beklagte wird verurteilt,

den nachfolgend wiedergegebenen, am 16. Januar 2018 gelöschten Beitrag des Klägers wieder freizuschalten ("Post 1"):

den nachfolgend wiedergegebenen, am 22. Februar 2018 gelöschten Beitrag des Klägers wieder freizuschalten ("Post 2"):

den nachfolgend wiedergegebenen, am 8. Juni 2018 gelöschten Beitrag des Klägers wieder freizuschalten ("Post 4"):

 "Betreibe einfach kommando krav maga (Stufe 2!) dann können musels ruhig antraben"

den nachfolgend wiedergegebenen, am 26. Juni 2018 gelöschten Beitrag des Klägers wieder freizuschalten ("Post 5"):

es zu unterlassen, den Kläger für das Einstellen des unter Ziffer 1 genannten Bildes oder Textes auf www.f.         

         .com erneut zu sperren oder den Beitrag zu löschen. Für den Fall der Zuwiderhandlung wird der Beklagten Ordnungsgeld von bis zu 250.000 €, ersatzweise Ordnungshaft, oder Ordnungshaft bis zu sechs Monaten angedroht, wobei die Ordnungshaft an ihren Vorstandsmitgliedern zu vollziehen ist.`

export const languages: string[] = [
  "Abchasisch",
  "Afar",
  "Afrikaans",
  "Akan",
  "Albanisch",
  "Altkirchenslawisch",
  "Amharisch",
  "Arabisch",
  "Aragonesisch",
  "Armenisch",
  "Aserbaidschanisch",
  "Assamesisch",
  "Avarisch",
  "Avestisch",
  "Aymara",
  "Bambara",
  "Baschkirisch",
  "Baskisch",
  "Belarussisch",
  "Belgisches Niederländisch",
  "Bengalisch",
  "Bihari",
  "Birmanisch",
  "Bislama",
  "Bokmål",
  "Bosnisch",
  "Bretonisch",
  "Bulgarisch",
  "Bündnerromanisch",
  "Chamorro",
  "Chichewa",
  "Chinesisch",
  "Cree",
  "Dänisch",
  "Deutsch",
  "Dhivehi",
  "Dzongkha",
  "Englisch",
  "Esperanto",
  "Estnisch",
  "Ewe",
  "Färöisch",
  "Fidschi",
  "Finnisch",
  "Französisch",
  "Fulfulde",
  "Galicisch",
  "Georgisch",
  "Griechisch",
  "Grönländisch",
  "Guaraní",
  "Gujarati",
  "Haitianisch-Kreolisch",
  "Hausa",
  "Hebräisch",
  "Hindi",
  "Hiri Motu",
  "Ido",
  "Igbo",
  "Indonesisch",
  "Interlingua",
  "Interlingue",
  "Inuktitut",
  "Inupiaq",
  "Irisch",
  "isiXhosa",
  "isiZulu",
  "Isländisch",
  "Italienisch",
  "Japanisch",
  "Javanisch",
  "Jiddisch",
  "Kalaallisut",
  "Kannada",
  "Kanuri",
  "Kasachisch",
  "Kashmiri",
  "Kastilisch",
  "Katalanisch",
  "Khmer",
  "Kikongo",
  "Kikuyu",
  "Kiluba",
  "Kinyarwanda",
  "Kirchenslawisch",
  "Kirgisisch",
  "Kirundi",
  "Komi",
  "Koreanisch",
  "Kornisch",
  "Korsisch",
  "Kroatisch",
  "Kurdisch",
  "Laotisch",
  "Latein",
  "Lettisch",
  "Limburgisch",
  "Lingála",
  "Litauisch",
  "Luganda",
  "Luxemburgisch",
  "Malagasy",
  "Malaiisch",
  "Malayalam",
  "Maltesisch",
  "Manx",
  "Manx-Gälisch",
  "Maori",
  "Marathi",
  "Marshallesisch",
  "Mazedonisch",
  "Mongolisch",
  "Nauruisch",
  "Navajo",
  "Ndonga",
  "Nepali",
  "Niederländisch",
  "Nord-Ndebele",
  "Nordsamisch",
  "Norwegisch",
  "Nynorsk",
  "Ojibwe",
  "Okzitanisch",
  "Oriya",
  "Oromo",
  "oshiKwanyama",
  "Ossetisch",
  "Otjiherero",
  "Pali",
  "Panjabi",
  "Paschtunisch",
  "Persisch",
  "Polnisch",
  "Portugiesisch",
  "Quechua",
  "Romanisch",
  "Ruandisch",
  "Rumänisch",
  "Russisch",
  "Samoanisch",
  "Sango",
  "Sanskrit",
  "Sardisch",
  "Schottisch-gälisch",
  "Schwedisch",
  "Serbisch",
  "Serbokroatisch",
  "Sesotho",
  "Setswana",
  "Shona",
  "Sindhi",
  "Singhalesisch",
  "Siswati",
  "Slowakisch",
  "Slowenisch",
  "Somali",
  "Spanisch",
  "Süd-Ndebele",
  "Süd-Sotho",
  "Sundanesisch",
  "Swahili",
  "Tadschikisch",
  "Tagalog",
  "Tahitianisch",
  "Tahitisch",
  "Tamil",
  "Tatarisch",
  "Telugu",
  "Thai",
  "Tibetisch",
  "Tigrinya",
  "Tongaisch",
  "Tschechisch",
  "Tschetschenisch",
  "Tschuwaschisch",
  "Tshivenda",
  "Türkisch",
  "Turkmenisch",
  "Twi",
  "Uigurisch",
  "Ukrainisch",
  "Ungarisch",
  "Urdu",
  "Usbekisch",
  "Valencianisch",
  "Vietnamesisch",
  "Volapük",
  "Walisisch",
  "Wallonisch",
  "Westfriesisch",
  "Wolof",
  "Xitsonga",
  "Yi",
  "Yoruba",
  "Zhuang",
]
