otc:
  obs:
    bucket-name: neuris-document-storage-staging

error:
  nodes:
    active: true

spring:
  data:
    redis:
      host: redis
      username: redis

database:
  seed: true

sentry:
  dsn: ${SENTRY_DSN}
  environment: staging
  traces-sample-rate: 0

neuris:
  environment: staging
  document-number-patterns:
    DS: XXRE0******YY
    CC-RIS: XXRE1******YY
    BGH: XXRE2******YY
    BVerfG: XXRE3******YY
    BVerwG: XXRE4******YY
    BSG: XXRE5******YY
    BFH: XXRE6******YY
    BFH-Anh: XXRE6******YY
    BPatG: XXRE7******YY
    BAG: XXRE8****YYYY
