application:
  name: NeuRIS Rechtsinformationssystem
  description: API service
error:
  nodes:
    active: false
info:
  git:
    enabled: true
    mode: full
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          include: readinessState,redis,db
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

otc:
  obs:
    endpoint: https://obs.eu-de.otc.t-systems.com

sentry:
  exception-resolver-order: -2147483647
  ignored-exceptions-for-type:
    - org.springframework.security.authorization.AuthorizationDeniedException
    - de.bund.digitalservice.ris.caselaw.domain.exception.DocumentationUnitNotExistsException
    - org.apache.catalina.connector.ClientAbortException # client closed connection, e.g. combobox
    - org.springframework.web.context.request.async.AsyncRequestNotUsableException # client closed connection, e.g. combobox

server:
  shutdown: graceful
  servlet:
    session:
      cookie:
        max-age: 43200 # 12*60*60
        http-only: false
      timeout: 43200 # 12*60*60
logging:
  structured:
    format:
      console: logstash
#  level:
#    org.springframework: DEBUG
#    org.hibernate.SQL: DEBUG
#    sql: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.type: TRACE
#    org.hibernate.orm.jdbc.bind: trace
spring:
  codec:
    max-in-memory-size: 100MB
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    #    show-sql: true
    properties:
      hibernate:
        #        format_sql: true
        #        highlight_sql: true
        #        use_sql_comments: true
        #        type: trace
        dialect=org.hibernate.dialect.PostgreSQLDialect:
        query:
          #          fail_on_pagination_over_collection_fetch: true
          default_batch_fetch_size: 20
          batch_fetch_style: dynamic
  security:
    oauth2:
      client:
        registration:
          oidcclient:
            provider: keycloak
            scope:
              - openid
              - profile
              - email
          bareid-user-api-client:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_basic

springdoc:
  api-docs:
    path: /api/docs.json
  swagger-ui:
    path: /api/docs.html

unleash:
  appName: unleash-proxy

neuris:
  document-number-patterns:
    BGH: KORE7****YYYY # results in e.g. KORE 7 0001 2024
    BVerfG: KVRE*****YY41 # results in e.g. KVRE 00001 24 41
    BVerwG: WBRE6****YYYY
    BSG: KSRE1******YY
    DS: XXRE0******YY
    DS-Anh: XXAH0******YY
    CC-RIS: XXRE1******YY
    CC-RIS-Anh: XXAH1******YY
    BFH: STREYYYY2****
    BFH-Anh: STAHYYYY2****
    BPatG: MPRE6******YY
    BAG: KARE7****YYYY

languagetool:
  url: http://languagetool:8181/v2/check
  language: de-DE
  enabled: true
  disabledRules:
    - UPPERCASE_SENTENCE_START
  disabledCategories:
    - EMPFOHLENE_RECHTSCHREIBUNG
    - GENDER_NEUTRALITY
    - COMPOUNDING
    - GRAMMAR
    - HILFESTELLUNG_KOMMASETZUNG
    - CONFUSED_WORDS
    - MULTITOKEN_SPELLING
    - IDIOMS
    - SEMANTICS
    - MISC
    - STYLE
    - TYPOGRAPHY
    - COLLOQUIALISMS
    - REPETITIONS_STYLE
    - WIKIPEDIA
    - PLAIN_ENGLISH
    - FALSE_FRIENDS
    - REPETITIONS
    - REGIONALISMUS
  disabledCategoriesWithWhitelistedRules:
    REDUNDANCY:
      - GERMAN_WORD_REPEAT_RULE
    PUNCTUATION:
      - DE_UNPAIRED_QUOTES

eurlex:
  url: ${EURLEX_URL}

bareid:
  instance: ${BAREID_INSTANCE}
