application:
  name: NeuRIS Rechtsinformationssystem
  description: API service
error:
  nodes:
    active: false
info:
  git:
    enabled: true
    mode: full
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          include: readinessState,redis,db
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

otc:
  obs:
    endpoint: https://obs.eu-de.otc.t-systems.com

sentry:
  exception-resolver-order: -2147483647
  ignored-exceptions-for-type: org.springframework.security.authorization.AuthorizationDeniedException,de.bund.digitalservice.ris.caselaw.domain.exception.DocumentationUnitNotExistsException,org.apache.catalina.connector.ClientAbortException

server:
  shutdown: graceful
  servlet:
    session:
      cookie:
        max-age: 43200 # 12*60*60
        http-only: false
      timeout: 43200 # 12*60*60
#logging:
#  level:
#    org.springframework: DEBUG
spring:
  codec:
    max-in-memory-size: 100MB
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          oidcclient:
            provider: keycloak
            scope:
              - openid
              - profile
              - email

springdoc:
  api-docs:
    path: /api/docs.json
  swagger-ui:
    path: /api/docs.html

unleash:
  appName: unleash-proxy

neuris:
  document-number-patterns:
    BGH: KORE7****YYYY # results in e.g. KORE 7 0001 2024
    BVerfG: KVRE*****YY41 # results in e.g. KVRE 00001 24 41
    BVerwG: WBRE61*****YY # TODO where put user und year?
    BSG: KSRE1******YY
    DS: XXRE0******YY
    CC-RIS: XXRE1******YY
    BFH: STREYYYY2****
    BPatG: MPRE6******YY
    BAG: KARE7****YYYY
    # TODO: other docoffices
