otc:
  obs:
    bucket-name: neuris-document-storage-production

spring:
  data:
    redis:
      host: redis
      username: redis

sentry:
  dsn: ${SENTRY_DSN}
  environment: production
  traces-sample-rate: 0.01

neuris:
  environment: production
  portalUrl: https://testphase.rechtsinformationen.bund.de/
  document-number-patterns:
    BGH: KORE7****YYYY # results in e.g. KORE 7 0001 2024
    BVerfG: KVRE*****YY42 # results in e.g. KVRE 00001 24 42
    BVerwG: WBRE7****YYYY
    BSG: BSGRE0*****YY
    DS: XXRE0******YY
    DS-Anh: XXAH0******YY
    CC-RIS: XXRE1******YY
    CC-RIS-Anh: XXAH1******YY
    BFH: STREYYYY2****
    BFH-Anh: STAHYYYY2****
    BPatG: MPRE6******YY
    BAG: KARE7****YYYY
