on:
  workflow_call:

jobs:
  e2e-matrix:
    strategy:
      fail-fast: false
      matrix:
        project: [ chromium, firefox ]
    uses: ./.github/workflows/e2e-sharding-matrix.yml
    with:
      project: ${{ matrix.project }}
    secrets: inherit
