on:
  workflow_call:

jobs:
  e2e-matrix:
    if: ${{ github.ref == 'refs/heads/main' }}
    strategy:
      fail-fast: false
      matrix:
        project: [ chromium, firefox, a11y ]
    uses: ./.github/workflows/_playwright-test.yml
    with:
      project: ${{ matrix.project }}
    secrets: inherit
