FROM node:16.14.2 AS builder
WORKDIR /usr/src/app
COPY . .
RUN npm install && npx vite build


FROM nginx:1.23.1-alpine
EXPOSE 80
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf